CREATE TABLE pedidos (
    id SERIAL PRIMARY KEY,
    comprador_id INT NOT NULL,
    nome_comprador VARCHAR(100) NOT NULL,
    email_comprador VARCHAR(100) NOT NULL,
    cpf_comprador VARCHAR(14) NOT NULL,
    telefone_comprador VARCHAR(15) NOT NULL,
    pedido_id INT NOT NULL,
    produto_id INT NOT NULL,
    nome_produto VARCHAR(100) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    preco_unitario DECIMAL(10,2) NOT NULL CHECK (preco_unitario >= 0),
    quantidade INT NOT NULL CHECK (quantidade > 0),
    total DECIMAL(10,2) NOT NULL CHECK (total >= 0),
    metodo_pagamento VARCHAR(20) NOT NULL CHECK (metodo_pagamento IN ('Cartão de Crédito', 'Boleto', 'Pix')),
    status_pedido VARCHAR(20) NOT NULL CHECK (status_pedido IN ('Em Processamento', 'Aprovado', 'Enviado', 'Entregue', 'Cancelado')),
    data_pedido TIMESTAMP NOT NULL,
    enderecos_entrega VARCHAR(200) NOT NULL,
    transportadora VARCHAR(50) NOT NULL,
    codigo_rastreamento VARCHAR(20),
    status_envio VARCHAR(25) NOT NULL CHECK (status_envio IN ('Aguardando Processamento', 'Em Separação', 'Em Trânsito', 'Entregue', 'Cancelado')),
    vendedor_id INT NOT NULL,
    nome_vendedor VARCHAR(100) NOT NULL,
    cnpj_vendedor VARCHAR(18) NOT NULL,
    telefone_vendedor VARCHAR(15) NOT NULL,
    endereco_vendedor VARCHAR(200) NOT NULL,
    data_entrega DATE,
    avaliacao INT CHECK (avaliacao >= 1 AND avaliacao <= 5),
    comentario TEXT
);